from __future__ import annotations

from datetime import datetime
from typing import Protocol

from backend.src.db.models import ChatRun, ChatSession, UploadJob, User


class UserRepository(Protocol):
    def get(self, user_id: str) -> User | None: ...
    def get_by_email(self, email: str) -> User | None: ...
    def create(self, email: str, password_hash: str, role: str = "user") -> User: ...
    def list(self, limit: int = 100) -> list[User]: ...


class RefreshTokenRepository(Protocol):
    def save(self, user_id: str, jti_hash: str, expires_at: datetime) -> None: ...
    def consume(self, jti_hash: str) -> str | None: ...
    def revoke(self, jti_hash: str) -> None: ...


class ChatRepository(Protocol):
    def create_session(self, session_id: str, user_id: str, message: str) -> ChatSession: ...
    def append_user_message(self, session_id: str, message: str) -> None: ...
    def create_run(self, run_id: str, session_id: str) -> ChatRun: ...
    def update_run(self, run_id: str, **updates) -> None: ...
    def update_session(self, session_id: str, **updates) -> None: ...
    def append_event(self, run_id: str, event: dict, status: str | None = None) -> None: ...
    def complete_run(self, run_id: str, answer: str, finished_at: datetime) -> None: ...
    def get_run(self, run_id: str) -> ChatRun | None: ...
    def get(self, session_id: str) -> ChatSession | None: ...
    def list(self, user_id: str | None, limit: int = 20) -> list[ChatSession]: ...
    def fail_stale(self, cutoff: datetime, finished_at: datetime) -> int: ...


class KnowledgeBaseRepository(Protocol):
    def get_version(self, user_id: str) -> int: ...
    def bump_version(self, user_id: str) -> int: ...


class UploadRepository(Protocol):
    def create(self, job_id: str, user_id: str, file_name: str, message: str, content_type: str | None = None, size_bytes: int | None = None) -> UploadJob: ...
    def update(self, job_id: str, **updates) -> None: ...
    def claim_retry(self, job_id: str, user_id: str | None = None) -> bool: ...
    def get(self, job_id: str) -> UploadJob | None: ...
    def list(self, user_id: str | None, limit: int = 20) -> list[UploadJob]: ...
    def fail_stale(self, cutoff: datetime, finished_at: datetime) -> int: ...


class DocumentRepository(Protocol):
    def upsert_from_upload(self, job: UploadJob) -> None: ...
    def delete_by_source(self, user_id: str, source: str) -> bool: ...


class GraphRepository(Protocol):
    def list_documents(self, limit: int = 20, owner_id: str | None = None) -> list[dict]: ...
    def get_document_graph(self, source: str, limit_chunks: int = 18, owner_id: str | None = None) -> dict: ...
    def delete_document(self, source: str, owner_id: str) -> bool: ...


class ObjectStorage(Protocol):
    def put_bytes(self, object_key: str, content: bytes, content_type: str = "application/octet-stream") -> str: ...
    def get_bytes(self, object_key: str) -> bytes: ...
    def put_path(self, object_key: str, path: str, content_type: str = "application/octet-stream") -> str: ...
